### PR TITLE
feat(types): allow configuring task payloads

### PR DESCRIPTION
**Pull request by joelmukuthu**
## Description

This PR makes the `Task` type generic, thereby allowing users to configure the exact shape of payloads.

## Performance impact

N/A

## Security impact

N/A

## Checklist

- [x] My code matches the project's code style and `yarn lint:fix` passes.
- [x] ~~I've added tests for the new feature, and `yarn test` passes~~
- [x] I have detailed the new feature in the relevant documentation.
- [x] I have added this feature to 'Pending' in the `RELEASE_NOTES.md` file (if one exists).
- [x] ~~If this is a breaking change I've explained why.~~

### CODE REVIEW

**Comment by benjie** [comment]
Thanks for the pull request, it seems to be an alternate implementation of #142. I'm not really happy adding this to tasks if there's no synchronised type definitions with addJob - otherwise there's not really any type safety here. Further there's no guarantee that the tasks are added with addJob, they might be created in the database directly, so any types applied to the payload cannot be trusted, hence why we currently type them as unknown. Basically - the pain of `unknown` is intentional so that you know you shouldn't be trusting the data you get from payload because it's not guaranteed to conform to your type definition. Currently we recommend you use `runtypes` or similar approaches to ensure that the payload does conform to the shape you're expecting before you go ahead and use it.

For previous work and discussions around this, please see:

- https://github.com/graphile/worker/issues/56
- https://github.com/graphile/worker/issues/57
- https://github.com/graphile/worker/pull/142

**Comment by joelmukuthu** [comment]
In my case the tasks are created in the database (which is why I missed the `addJob` use-case) and I would just like to document the shape of the payload in my TS code and of course have some type-checking there as well. It would be nice if this was opt-in -- with responsibility falling to the user once they opt in -- and I would also argue that while the shape of payloads is unknown to Graphile worker, it should be known to the user.

That said, I understand your reservations and motivation to protect users from foot-guns and that it's a non-trivial issue. So it's fine by me to close this :)

**Comment by benjie** [comment]
I'm kind of on the fence. I'm going to close this because we already have issues/PRs covering this topic, but I appreciate you adding your +1. I wouldn't be surprised if I give in and add types in the next 12 months or so :shrug:

**Comment by joelmukuthu** [comment]
No worries! Thank you so much for your continued efforts on OSS! :heart:

**Pull request closed without merging**
