### PR TITLE
Add example for Faktory #7

### PR DESCRIPTION
**Pull request by madflow**
* I experimented with exporting Postgres `NOTIFY` events to  [Faktory](https://github.com/contribsys/faktory) because I could not find a Postgres job queue that would meet my needs. So this is a rip-off from that work.
* I was not quite sure I a task function should throw on an error or return something to fail the job...

### CODE REVIEW

**Comment by benjie** [comment]
LGTM 👍 

And yes, the tasks should throw on error.

**Comment by benjie** [comment]
Thanks for this @madflow; this is going to be a great place to point people to when they ask about similar tasks.

**Comment by benjie** [comment]
Does Faktory have a unique identifier for jobs? Was wondering if it was worth using that to enforce idempotency - at the moment if `await faktoryClient.close();` throws then the job will be re-queued and may be added to Faktory multiple times.

**Comment by madflow** [comment]
You can provide the `jid` in the job payload, which is a unique identifier. You are right - this would be worth using.  I will investigate :running_man: .

**Comment by benjie** [comment]
You can het our job id from `helpers.job.id` 👍

**Comment by madflow** [comment]
It turns out, that unique jobs are a "Pro" feature: https://github.com/contribsys/faktory/wiki/Pro-Unique-Jobs

It is possible to pass the jid in the job payload - but you can do this multiple times. There is no documented way I am aware of to check, if the current jid is already being processed by Faktory.

**Comment by benjie** [comment]
👍

**Pull request merged**
